/// Opponent assignment — the product backbone:
///
/// 1. **Online first**: try to open a real channel via Supabase. While the
///    lobby is not live (fresh Play Store launch, zero players) this
///    returns null immediately.
/// 2. **Simulated-human fallback**: seat a bot indistinguishable from a
///    person — names generated by `random_name_generator` (75% female,
///    localized per zone), flags consistent with the name's culture via
///    `country_pickers`, deterministic avatars (`random_avatar` seeds off
///    the name), rating near the player's + form-based nudges.
library;

import 'dart:math';

import 'package:random_name_generator/random_name_generator.dart';

import '../data/remote/supabase_service.dart';

class OpponentIdentity {
  final String name;
  final String flagIso; // ISO-3166 alpha-2, rendered via country_pickers
  final bool female;
  const OpponentIdentity(this.name, this.flagIso, this.female);
}

class _ZoneFlag {
  final Zone zone;
  final String iso;
  const _ZoneFlag(this.zone, this.iso);
}

class MatchmakingService {
  /// Name cultures we seat — flag always matches the name's zone.
  static const _pool = [
    _ZoneFlag(Zone.india, 'IN'),
    _ZoneFlag(Zone.us, 'US'),
    _ZoneFlag(Zone.uk, 'GB'),
    _ZoneFlag(Zone.germany, 'DE'),
    _ZoneFlag(Zone.france, 'FR'),
    _ZoneFlag(Zone.spain, 'ES'),
    _ZoneFlag(Zone.italy, 'IT'),
    _ZoneFlag(Zone.brazil, 'BR'),
    _ZoneFlag(Zone.russia, 'RU'),
    _ZoneFlag(Zone.poland, 'PL'),
    _ZoneFlag(Zone.turkey, 'TR'),
    _ZoneFlag(Zone.egypt, 'EG'),
    _ZoneFlag(Zone.china, 'CN'),
    _ZoneFlag(Zone.japan, 'JP'),
    _ZoneFlag(Zone.ukraine, 'UA'),
    _ZoneFlag(Zone.canada, 'CA'),
    _ZoneFlag(Zone.iran, 'IR'),
    _ZoneFlag(Zone.saudiArabia, 'SA'),
    _ZoneFlag(Zone.romania, 'RO'),
    _ZoneFlag(Zone.switzerland, 'CH'),
    _ZoneFlag(Zone.afghanistan, 'AF'),
    _ZoneFlag(Zone.southAfrica, 'ZA'),
    _ZoneFlag(Zone.uganda, 'UG'),
  ];

  static final Random _rng = Random();

  /// Priority #1: a real online opponent. Null until the lobby ships.
  static Future<OpponentIdentity?> tryOnline(int nearRating) async {
    if (!SupabaseService.isReady) return null;
    // Real matchmaking channel lands with the online update; until then
    // we never block the player — the fallback seats someone instantly.
    return null;
  }

  /// Priority #2: a believable human stand-in (mostly female names).
  static OpponentIdentity simulatedHuman(
    int nearRating, {
    int formBoost = 0,
  }) {
    final pick = _pool[_rng.nextInt(_pool.length)];
    final female = _rng.nextDouble() < 0.75;
    String name;
    try {
      final rn = RandomNames(pick.zone);
      name = female ? rn.womanFullName() : rn.manFullName();
    } catch (_) {
      // Unknown zone at runtime → neutral fallback name.
      name = female ? 'Aisha Khan' : 'Ali Khan';
    }
    final elo =
        (nearRating + _rng.nextInt(301) - 150 + formBoost).clamp(400, 2400);
    return OpponentIdentity(name, pick.iso, female);
  }

  /// Winning streak → slightly tougher opponents; losing streak → gentler.
  static int formBoostFor(List<String> form) {
    final last = form.length > 5 ? form.sublist(form.length - 5) : form;
    var d = 0;
    for (final r in last) {
      if (r == 'w') { d += 1; } else if (r == 'l') { d -= 1; } }
    return (d * 20).clamp(-60, 60);
  }
}
